#!/bin/sh

chown -R arduino:arduino /home/arduino/.local/share/arduino-app-cli

systemctl enable arduino-app-cli
systemctl enable arduino-burn-bootloader
systemctl enable arduino-avahi-serial.service
